name: Build Py-Auto-Migrate Binaries

on:
  push:
    tags:
      - "v*"   
  workflow_dispatch: 

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas tqdm pymysql pymongo mysqlSaver click psycopg2

      - name: Build binary
        run: |
          pyinstaller --onefile --name=py-auto-migrate py_auto_migrate/shell.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: py-auto-migrate-${{ runner.os }}
          path: dist/py-auto-migrate*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
